# 도커 최신버전 사용 지정
#### gunicorn 설치 후
version: '3'
services:
  web:
    build: .  # 현재 폴더의 Dockerfile 사용
    command: gunicorn django_tutorial.wsgi:application --bind 0.0.0.0:8000
    volumes:  # 현재 폴더를 /usr/src/app와 연결함.
      - static_volume:/usr/src/app/_static
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./envs/.env.dev
volumes:
  static_volume: (편집됨) 
