# Generated by Django 4.0.3 on 2022-03-17 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': '글 저장하기'},
        ),
    ]
